apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: research
  labels:
    name: research
---
apiVersion: v1
kind: Namespace
metadata:
  name: ds
  labels:
    name: ds
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    name: kafka
